site_name: 'Distracted Data'
site_description: 'Python, Data, Machine Learning, Raspberry Pi, and Distractions'
site_author: 'Mike Moran'
site_url: 'https://distracteddata.github.io'
copyright: 'Copyright &copy; 2017 Mike Moran'
pages:
    - Home: index.md
    - About: about.md
    - Python (coming soon): python.md
    - Pandas (coming soon): pandas.md
    - Machine Learning (coming soon): machine_learning.md
    - Data Visualization (coming soon): data_visualization.md
    - Raspberry Pi: RaspberryPi.md
theme: 'material' 
extra:
    palette:
        primary: 'red' 
        accent: 'deep orange'
    font:
        text: 'Roboto'
        code: 'Roboto Mono'
